-- Create Dynasties table
CREATE TABLE IF NOT EXISTS public.dynasties (
    id VARCHAR(50) PRIMARY KEY, -- e.g. 'tang', 'ming'
    name VARCHAR(100) NOT NULL, -- English name
    chinese_name VARCHAR(50) NOT NULL,
    start_year INTEGER NOT NULL,
    end_year INTEGER NOT NULL,
    color VARCHAR(7) NOT NULL DEFAULT '#888888',
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS for Dynasties
ALTER TABLE public.dynasties ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.dynasties FOR SELECT USING (true);
CREATE POLICY "Enable write access for authenticated users only" ON public.dynasties FOR ALL USING (auth.role() = 'authenticated');

-- Create Historical Events table
CREATE TABLE IF NOT EXISTS public.historical_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year INTEGER NOT NULL,
    title VARCHAR(200) NOT NULL,
    event_type VARCHAR(20) DEFAULT 'politics', -- war, culture, politics, science
    description TEXT,
    importance INTEGER DEFAULT 3 CHECK (importance >= 1 AND importance <= 5),
    dynasty_id VARCHAR(50) REFERENCES public.dynasties(id) ON DELETE SET NULL,
    source_reference VARCHAR(200),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS for Historical Events
ALTER TABLE public.historical_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.historical_events FOR SELECT USING (true);
CREATE POLICY "Enable write access for authenticated users only" ON public.historical_events FOR ALL USING (auth.role() = 'authenticated');

-- Create River Pins (Podcast Tracks) table
-- Note: 'jobs' table already exists and links to podcasts. This is for the 'timeline' view.
CREATE TABLE IF NOT EXISTS public.river_pins (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    job_id VARCHAR(36) NOT NULL, -- Link to job/podcast
    title VARCHAR(200) NOT NULL,
    year INTEGER NOT NULL,
    douban_rating DECIMAL(3, 1),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS for River Pins
ALTER TABLE public.river_pins ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.river_pins FOR SELECT USING (true);
CREATE POLICY "Enable write access for authenticated users only" ON public.river_pins FOR ALL USING (auth.role() = 'authenticated');

-- Create Event Cache table (for AI responses)
CREATE TABLE IF NOT EXISTS public.timeline_event_cache (
    uuid VARCHAR(64) PRIMARY KEY, -- SHA256 hash
    year INTEGER NOT NULL,
    event_title VARCHAR(200) DEFAULT '',
    context TEXT,
    content TEXT,
    is_cached BOOLEAN DEFAULT TRUE,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS for Event Cache
ALTER TABLE public.timeline_event_cache ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.timeline_event_cache FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON public.timeline_event_cache FOR INSERT WITH CHECK (true); -- Allow frontend to cache? Or restrict to service role?
-- For now, let's restrict write to authenticated or service role. Actually, if we use Vercel API, it will use service role.
-- But if we want frontend to directly read, we need SELECT policy.
