# Generated by Django 4.2.17 on 2025-11-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riverpin',
            options={'ordering': ['year'], 'verbose_name': '播客轨道', 'verbose_name_plural': '播客轨道管理'},
        ),
        migrations.RenameIndex(
            model_name='riverpin',
            new_name='river_pins_year_9bdcbf_idx',
            old_name='river_pins_year_idx',
        ),
        migrations.AlterField(
            model_name='riverpin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='riverpin',
            name='job_id',
            field=models.CharField(max_length=36, verbose_name='任务ID'),
        ),
        migrations.AlterField(
            model_name='riverpin',
            name='title',
            field=models.CharField(max_length=200, verbose_name='书籍名称'),
        ),
        migrations.AlterField(
            model_name='riverpin',
            name='year',
            field=models.IntegerField(verbose_name='年份'),
        ),
    ]
