# Generated by Django 4.2.26 on 2025-11-26 02:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_alter_riverpin_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dynasty',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='朝代ID')),
                ('name', models.CharField(max_length=100, verbose_name='英文名称')),
                ('chinese_name', models.CharField(max_length=50, verbose_name='中文名称')),
                ('start_year', models.IntegerField(verbose_name='开始年份')),
                ('end_year', models.IntegerField(verbose_name='结束年份')),
                ('color', models.CharField(help_text='如: #ff0000', max_length=7, verbose_name='颜色代码')),
                ('description', models.TextField(verbose_name='朝代描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '朝代',
                'verbose_name_plural': '朝代管理',
                'db_table': 'dynasties',
                'ordering': ['start_year'],
            },
        ),
        migrations.AlterModelOptions(
            name='riverpin',
            options={'ordering': ['year'], 'verbose_name': '播客轨道(已弃用)', 'verbose_name_plural': '播客轨道管理(已弃用)'},
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='负数表示公元前', verbose_name='年份')),
                ('title', models.CharField(max_length=200, verbose_name='事件标题')),
                ('event_type', models.CharField(choices=[('war', '战争'), ('culture', '文化'), ('politics', '政治'), ('science', '科技')], default='politics', max_length=20, verbose_name='事件类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='事件描述')),
                ('importance', models.IntegerField(choices=[(1, '极其重要'), (2, '非常重要'), (3, '重要'), (4, '一般'), (5, '次要')], default=3, help_text='1=极其重要, 5=次要', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='重要性等级')),
                ('source_reference', models.CharField(blank=True, help_text='记录史料出处或参考来源', max_length=200, verbose_name='史料来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dynasty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='timeline.dynasty', verbose_name='所属朝代')),
            ],
            options={
                'verbose_name': '历史事件',
                'verbose_name_plural': '历史事件管理',
                'db_table': 'historical_events',
                'ordering': ['year', 'importance', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='dynasty',
            index=models.Index(fields=['start_year', 'end_year'], name='dynasties_start_y_bdd085_idx'),
        ),
        migrations.AddIndex(
            model_name='dynasty',
            index=models.Index(fields=['name'], name='dynasties_name_8b03e1_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalevent',
            index=models.Index(fields=['year'], name='historical__year_c6f7b7_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalevent',
            index=models.Index(fields=['event_type'], name='historical__event_t_0cbcaa_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalevent',
            index=models.Index(fields=['importance'], name='historical__importa_171dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalevent',
            index=models.Index(fields=['year', 'importance'], name='historical__year_847110_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalevent',
            index=models.Index(fields=['dynasty'], name='historical__dynasty_9c4001_idx'),
        ),
        migrations.AddConstraint(
            model_name='historicalevent',
            constraint=models.CheckConstraint(check=models.Q(('importance__gte', 1), ('importance__lte', 5)), name='importance_between_1_and_5'),
        ),
    ]
