# Generated by Django 4.2.26 on 2025-11-27 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_dynasty_alter_riverpin_options_historicalevent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riverpin',
            options={'ordering': ['year'], 'verbose_name': '播客轨道', 'verbose_name_plural': '播客轨道管理'},
        ),
    ]
