# Generated by Django 4.2.26 on 2025-11-28 04:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_add_uuid_to_riverpin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riverpin',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='EventCache',
            fields=[
                ('uuid', models.CharField(help_text="SHA-256 hash of 'title|year' or '__year__|year'", max_length=64, primary_key=True, serialize=False)),
                ('year', models.IntegerField(db_index=True, help_text='Historical year (negative for BCE)')),
                ('event_title', models.CharField(blank=True, default='', help_text='Event title (empty for year overviews)', max_length=200)),
                ('context', models.TextField(help_text='Query context passed to DeepSeek')),
                ('content', models.TextField(help_text='DeepSeek API response content')),
                ('is_cached', models.BooleanField(default=True, help_text='Whether this is cached (vs. directly fetched)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag for cache invalidation')),
            ],
            options={
                'verbose_name': '事件详情缓存',
                'verbose_name_plural': '事件详情缓存',
                'db_table': 'timeline_event_cache',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['year', 'event_title'], name='timeline_ev_year_201d84_idx'), models.Index(fields=['created_at'], name='timeline_ev_created_a65036_idx')],
            },
        ),
    ]
