# Generated by Django 4.2.26 on 2025-11-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_alter_riverpin_id_eventcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='riverpin',
            name='douban_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='例如: 8.5（0-10分）', max_digits=3, null=True, verbose_name='豆瓣评分'),
        ),
    ]
